language: python
#version
python:
  - "3.6.2"


before_install:
 - chmod +x tests/run_travis.sh

 #dependacies and libraries to install
  - pip3 install -r requirements.txt


branches:
  only:
    - master
    - deploy2


script:
 - tests/run_travis.sh


# whitelist



# command to run tests

after_success:
  -coveralls